package com.sinoway.rpt.entity;

import java.io.File;
import java.util.List;
import java.util.Map;
// default package
// Generated 2015-12-14 16:02:10 by Hibernate Tools 3.4.0.CR1

import com.sinoway.common.entity.PageModel;

/**
 * WfDatCerditrpt generated by hbm2java
 */
public class WfDatCreditrptUtil{

	/**
	 * 
	 */
	private String rptid;
	private String redorptid;
	private String fntjrn;
	private String prsnnam;
	private String credtyp;
	private String credtno;
	private String prsncod;
	private String telno;
	private String rpttyp;
	private String rptnam;
	private String prdcod;
	private String prdnam;
	private String datcmitori;
	private String rptdte;
	private String rpttim;
	private String rptsta;
	private String rptmoddte;
	private String rptmodtim;
	private String peoplecode;
	private String parntcode;
	private String orgno;
	private String reqadrr;
	private String rtpadrr;
	private List trns;
	private File file;
	private String fileFileName;
	private String fileStream;
	private String email;
	private String retPam;
	private String isverif;
	private String tradeinf;
	private String showtype;
	private String serpwd;//服务密码
	private String bcardno;//银行卡号
	private String bank;//发卡行
	private String company;//工作单位
	private String compaddr;//单位地址
	private String worktel;//工作电话
	private String tbacc;//淘宝账号
	private String tbpwd;//淘宝账号密码
	private String jdacc;//京东账号
	private String jdpwd;//京东账号密码
	// 预警查询核心人员编码
	private String usrid;
	// 预警查询核心父人员编码
	private String pusrid;
	// 预警查询核心机构号
	private String corgno;
	// 预警查询核心父机构号
	private String cporgno;
	private String appcod;
	
	private String cbcreports;
	private String newrptid;
	private String datavar;
	private String jsonpar;
	private String prttyp;
	private String bankName;
	private String bankCode;
	private String oldprdcod;
	private RptSearch rptSearch;
	private PageModel pageModel;
	private List<WfDatCreditrpt> rptList;
	private String pageStr;
	private String rptStr;
	private String ids;
	private TransString transstring;
	
	public TransString getTransstring() {
		return transstring;
	}

	public void setTransstring(TransString transstring) {
		this.transstring = transstring;
	}

	public String getIds() {
		return ids;
	}

	public void setIds(String ids) {
		this.ids = ids;
	}

	public List<WfDatCreditrpt> getRptList() {
		return rptList;
	}

	public void setRptList(List<WfDatCreditrpt> rptList) {
		this.rptList = rptList;
	}
	public RptSearch getRptSearch() {
		return rptSearch;
	}

	public void setRptSearch(RptSearch rptSearch) {
		this.rptSearch = rptSearch;
	}

	public PageModel getPageModel() {
		return pageModel;
	}

	public void setPageModel(PageModel pageModel) {
		this.pageModel = pageModel;
	}

	public String getRptStr() {
		return rptStr;
	}

	public void setRptStr(String rptStr) {
		this.rptStr = rptStr;
	}

	public String getPageStr() {
		return pageStr;
	}

	public void setPageStr(String pageStr) {
		this.pageStr = pageStr;
	}
	public String getAppcod() {
		return appcod;
	}

	public void setAppcod(String appcod) {
		this.appcod = appcod;
	}

	public String getPeoplecode() {
		return peoplecode;
	}

	public void setPeoplecode(String peoplecode) {
		this.peoplecode = peoplecode;
	}

	public String getParntcode() {
		return parntcode;
	}

	public void setParntcode(String parntcode) {
		this.parntcode = parntcode;
	}

	public String getSerpwd() {
		return serpwd;
	}

	public void setSerpwd(String serpwd) {
		this.serpwd = serpwd;
	}

	public String getBcardno() {
		return bcardno;
	}

	public void setBcardno(String bcardno) {
		this.bcardno = bcardno;
	}

	public String getBank() {
		return bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getCompaddr() {
		return compaddr;
	}

	public void setCompaddr(String compaddr) {
		this.compaddr = compaddr;
	}

	public String getWorktel() {
		return worktel;
	}

	public void setWorktel(String worktel) {
		this.worktel = worktel;
	}

	public String getTbacc() {
		return tbacc;
	}

	public void setTbacc(String tbacc) {
		this.tbacc = tbacc;
	}

	public String getTbpwd() {
		return tbpwd;
	}

	public void setTbpwd(String tbpwd) {
		this.tbpwd = tbpwd;
	}

	public String getJdacc() {
		return jdacc;
	}

	public void setJdacc(String jdacc) {
		this.jdacc = jdacc;
	}

	public String getJdpwd() {
		return jdpwd;
	}

	public void setJdpwd(String jdpwd) {
		this.jdpwd = jdpwd;
	}

	public String getShowtype() {
		return showtype;
	}

	public void setShowtype(String showtype) {
		this.showtype = showtype;
	}

	public String getTradeinf() {
		return tradeinf;
	}

	public void setTradeinf(String tradeinf) {
		this.tradeinf = tradeinf;
	}

	public String getIsverif() {
		return isverif;
	}

	public void setIsverif(String isverif) {
		this.isverif = isverif;
	}

	public String getRetPam() {
		return retPam;
	}

	public void setRetPam(String retPam) {
		this.retPam = retPam;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	public String getFileStream() {
		return fileStream;
	}

	public void setFileStream(String fileStream) {
		this.fileStream = fileStream;
	}

	public String getFileFileName() {
		return fileFileName;
	}

	public void setFileFileName(String fileFileName) {
		this.fileFileName = fileFileName;
	}

	public File getFile() {
		return file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	
	public List getTrns() {
		return trns;
	}

	public void setTrns(List trns) {
		this.trns = trns;
	}

	public WfDatCreditrptUtil() {
	}

	public WfDatCreditrptUtil(String rptid, String prsnnam, String prsncod) {
		this.rptid = rptid;
		this.prsnnam = prsnnam;
		this.prsncod = prsncod;
	}

	public WfDatCreditrptUtil(String rptid, String redorptid, String fntjrn, String prsnnam, String credtyp, String credtno,
			String prsncod, String telno, String rpttyp, String rptnam, String prdcod, String prdnam, String datcmitori,
			String rptdte, String rpttim, String rptsta, String rptmoddte, String rptmodtim,
			String orgno,  String reqadrr, String rtpadrr,String usrid,String pusrid,String corgno,String cporgno) {
		this.rptid = rptid;
		this.redorptid = redorptid;
		this.fntjrn = fntjrn;
		this.prsnnam = prsnnam;
		this.credtyp = credtyp;
		this.credtno = credtno;
		this.prsncod = prsncod;
		this.telno = telno;
		this.rpttyp = rpttyp;
		this.rptnam = rptnam;
		this.prdcod = prdcod;
		this.prdnam = prdnam;
		this.datcmitori = datcmitori;
		this.rptdte = rptdte;
		this.rpttim = rpttim;
		this.rptsta = rptsta;
		this.rptmoddte = rptmoddte;
		this.rptmodtim = rptmodtim;
		this.orgno = orgno;
		this.reqadrr = reqadrr;
		this.rtpadrr = rtpadrr;
		this.usrid = usrid;
		this.pusrid = pusrid;
		this.corgno = corgno;
		this.cporgno= cporgno;
	}

	public String getRptid() {
		return this.rptid;
	}

	public void setRptid(String rptid) {
		this.rptid = rptid;
	}

	public String getRedorptid() {
		return this.redorptid;
	}

	public void setRedorptid(String redorptid) {
		this.redorptid = redorptid;
	}

	public String getFntjrn() {
		return this.fntjrn;
	}

	public void setFntjrn(String fntjrn) {
		this.fntjrn = fntjrn;
	}

	public String getPrsnnam() {
		return this.prsnnam;
	}

	public void setPrsnnam(String prsnnam) {
		this.prsnnam = prsnnam;
	}

	public String getCredtyp() {
		return this.credtyp;
	}

	public void setCredtyp(String credtyp) {
		this.credtyp = credtyp;
	}

	public String getCredtno() {
		return this.credtno;
	}

	public void setCredtno(String credtno) {
		this.credtno = credtno;
	}

	public String getPrsncod() {
		return this.prsncod;
	}

	public void setPrsncod(String prsncod) {
		this.prsncod = prsncod;
	}

	public String getTelno() {
		return this.telno;
	}

	public void setTelno(String telno) {
		this.telno = telno;
	}

	public String getRpttyp() {
		return this.rpttyp;
	}

	public void setRpttyp(String rpttyp) {
		this.rpttyp = rpttyp;
	}

	public String getRptnam() {
		return this.rptnam;
	}

	public void setRptnam(String rptnam) {
		this.rptnam = rptnam;
	}

	public String getPrdcod() {
		return this.prdcod;
	}

	public void setPrdcod(String prdcod) {
		this.prdcod = prdcod;
	}

	public String getPrdnam() {
		return this.prdnam;
	}

	public void setPrdnam(String prdnam) {
		this.prdnam = prdnam;
	}

	public String getDatcmitori() {
		return this.datcmitori;
	}

	public void setDatcmitori(String datcmitori) {
		this.datcmitori = datcmitori;
	}

	public String getRptdte() {
		return this.rptdte;
	}

	public void setRptdte(String rptdte) {
		this.rptdte = rptdte;
	}

	public String getRpttim() {
		return this.rpttim;
	}

	public void setRpttim(String rpttim) {
		this.rpttim = rpttim;
	}

	public String getRptsta() {
		return this.rptsta;
	}

	public void setRptsta(String rptsta) {
		this.rptsta = rptsta;
	}

	public String getRptmoddte() {
		return this.rptmoddte;
	}

	public void setRptmoddte(String rptmoddte) {
		this.rptmoddte = rptmoddte;
	}

	public String getRptmodtim() {
		return this.rptmodtim;
	}

	public void setRptmodtim(String rptmodtim) {
		this.rptmodtim = rptmodtim;
	}


	public String getOrgno() {
		return this.orgno;
	}

	public void setOrgno(String orgno) {
		this.orgno = orgno;
	}


	public String getReqadrr() {
		return this.reqadrr;
	}

	public void setReqadrr(String reqadrr) {
		this.reqadrr = reqadrr;
	}

	public String getRtpadrr() {
		return this.rtpadrr;
	}

	public void setRtpadrr(String rtpadrr) {
		this.rtpadrr = rtpadrr;
	}

	public String getUsrid() {
		return usrid;
	}

	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	public String getPusrid() {
		return pusrid;
	}

	public void setPusrid(String pusrid) {
		this.pusrid = pusrid;
	}

	public String getCorgno() {
		return corgno;
	}

	public void setCorgno(String corgno) {
		this.corgno = corgno;
	}

	public String getCporgno() {
		return cporgno;
	}

	public void setCporgno(String cporgno) {
		this.cporgno = cporgno;
	}

	public String getCbcreports() {
		return cbcreports;
	}

	public void setCbcreports(String cbcreports) {
		this.cbcreports = cbcreports;
	}

	public String getNewrptid() {
		return newrptid;
	}

	public void setNewrptid(String newrptid) {
		this.newrptid = newrptid;
	}

	public String getDatavar() {
		return datavar;
	}

	public void setDatavar(String datavar) {
		this.datavar = datavar;
	}

	public String getJsonpar() {
		return jsonpar;
	}

	public void setJsonpar(String jsonpar) {
		this.jsonpar = jsonpar;
	}

	public String getPrttyp() {
		return prttyp;
	}

	public void setPrttyp(String prttyp) {
		this.prttyp = prttyp;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankCode() {
		return bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getOldprdcod() {
		return oldprdcod;
	}

	public void setOldprdcod(String oldprdcod) {
		this.oldprdcod = oldprdcod;
	}

}
