package com.sinoway.common.entity;
// default package
// Generated 2016-1-8 10:46:42 by Hibernate Tools 3.4.0.CR1

/**
 * WfCfgrefTrnoutele generated by hbm2java
 */
public class WfCfgrefTrnoutele implements java.io.Serializable {

	private static final long serialVersionUID = -3139138237176342410L;
	private String id;
	private String trncod;
	private String chnlcod;
	private String elecod;
	private String pelecod;
	private String elenam;
	private String sort;
	private String maxlen;
	private String minlen;
	private String datatype;
	private String issbc;
	private String isnull;
	private String sta;

	public WfCfgrefTrnoutele() {
	}

	public WfCfgrefTrnoutele(String id, String trncod, String elecod) {
		this.id = id;
		this.trncod = trncod;
		this.elecod = elecod;
	}

	public WfCfgrefTrnoutele(String id, String trncod, String chnlcod, String elecod, String pelecod, String elenam,
			String sort, String maxlen, String minlen, String datatype, String issbc, String isnull, String sta) {
		this.id = id;
		this.trncod = trncod;
		this.chnlcod = chnlcod;
		this.elecod = elecod;
		this.pelecod = pelecod;
		this.elenam = elenam;
		this.sort = sort;
		this.maxlen = maxlen;
		this.minlen = minlen;
		this.datatype = datatype;
		this.issbc = issbc;
		this.isnull = isnull;
		this.sta = sta;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTrncod() {
		return this.trncod;
	}

	public void setTrncod(String trncod) {
		this.trncod = trncod;
	}

	public String getChnlcod() {
		return this.chnlcod;
	}

	public void setChnlcod(String chnlcod) {
		this.chnlcod = chnlcod;
	}

	public String getElecod() {
		return this.elecod;
	}

	public void setElecod(String elecod) {
		this.elecod = elecod;
	}

	public String getPelecod() {
		return this.pelecod;
	}

	public void setPelecod(String pelecod) {
		this.pelecod = pelecod;
	}

	public String getElenam() {
		return this.elenam;
	}

	public void setElenam(String elenam) {
		this.elenam = elenam;
	}

	public String getSort() {
		return this.sort;
	}

	public void setSort(String sort) {
		this.sort = sort;
	}

	public String getMaxlen() {
		return this.maxlen;
	}

	public void setMaxlen(String maxlen) {
		this.maxlen = maxlen;
	}

	public String getMinlen() {
		return this.minlen;
	}

	public void setMinlen(String minlen) {
		this.minlen = minlen;
	}

	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	public String getIssbc() {
		return this.issbc;
	}

	public void setIssbc(String issbc) {
		this.issbc = issbc;
	}

	public String getIsnull() {
		return this.isnull;
	}

	public void setIsnull(String isnull) {
		this.isnull = isnull;
	}

	public String getSta() {
		return this.sta;
	}

	public void setSta(String sta) {
		this.sta = sta;
	}

}
