
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.test.gzt;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-01-08T14:09:22.739+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */

@javax.jws.WebService(
                      serviceName = "QueryValidatorServicesService",
                      portName = "QueryValidatorServices",
                      targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn",
                      wsdlLocation = "http://gboss.id5.cn/services/QueryValidatorServices?wsdl",
                      endpointInterface = "com.test.gzt.QueryValidatorServices")
                      
public class QueryValidatorServicesImpl implements QueryValidatorServices {

    private static final Logger LOG = Logger.getLogger(QueryValidatorServicesImpl.class.getName());

    /* (non-Javadoc)
     * @see com.test.gzt.QueryValidatorServices#querySingle(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  type ,)java.lang.String  param )*
     */
    public java.lang.String querySingle(java.lang.String userName,java.lang.String password,java.lang.String type,java.lang.String param) { 
        LOG.info("Executing operation querySingle");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(type);
        System.out.println(param);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.gzt.QueryValidatorServices#queryBatch(java.lang.String  userName ,)java.lang.String  password ,)java.lang.String  type ,)java.lang.String  param )*
     */
    public java.lang.String queryBatch(java.lang.String userName,java.lang.String password,java.lang.String type,java.lang.String param) { 
        LOG.info("Executing operation queryBatch");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(type);
        System.out.println(param);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
