package com.sinoway.rpt.entity;
// default package
// Generated 2015-12-14 16:02:10 by Hibernate Tools 3.4.0.CR1

import com.yzj.wf.common.cache.CacheUtil;
import com.yzj.wf.common.cache.Cacheable;

/**
 * WfDatCerditrpt generated by hbm2java
 */
public class WfDatCreditrpt implements java.io.Serializable, Cacheable {

	private static final long serialVersionUID = 8647945202817882235L;

	public static final String CREDITRPT_RPTID = "rptid";
	public static final String CREDITRPT_REDORPTID = "redorptid";
	public static final String CREDITRPT_FNTJRN = "fntjrn";
	public static final String CREDITRPT_PRSNNAM = "prsnnam";
	public static final String CREDITRPT_CREDTYP = "credtyp";
	public static final String CREDITRPT_CREDTNO = "credtno";
	public static final String CREDITRPT_PRSNCOD = "prsncod";
	public static final String CREDITRPT_TELNO = "telno";
	public static final String CREDITRPT_RPTTYP = "rpttyp";
	public static final String CREDITRPT_RPTNAM = "rptnam";
	public static final String CREDITRPT_PRDCOD = "prdcod";
	public static final String CREDITRPT_PRDNAM = "prdnam";
	public static final String CREDITRPT_DATCMITORI = "datcmitori";
	public static final String CREDITRPT_RPTDTE = "rptdte";
	public static final String CREDITRPT_RPTTIM = "rpttim";
	public static final String CREDITRPT_RPTSTA = "rptsta";
	public static final String CREDITRPT_RPTMODDTE = "rptmoddte";
	public static final String CREDITRPT_RPTMODTIM = "rptmodtim";
	public static final String CREDITRPT_PEOPLECODE = "peoplecode";
	public static final String CREDITRPT_ORGNO = "orgno";
	public static final String CREDITRPT_PARNTCODE = "parntcode";
	
	private String rptid;
	private String redorptid;
	private String fntjrn;
	private String prsnnam;
	private String credtyp;
	private String credtno;
	private String prsncod;
	private String telno;
	private String rpttyp;
	private String rptnam;
	private String prdcod;
	private String prdnam;
	private String datcmitori;
	private String rptdte;
	private String rpttim;
	private String rptsta;
	private String rptmoddte;
	private String rptmodtim;
	private String peoplecode;
	private String orgno;
	private String parntcode;
	private String reqadrr;
	private String rtpadrr;
	
	private String usrid;
	private String p_usrid;
	private String corgno;
	private String cporgno;
	

	public WfDatCreditrpt() {
	}

	public WfDatCreditrpt(String rptid, String prsnnam, String prsncod) {
		this.rptid = rptid;
		this.prsnnam = prsnnam;
		this.prsncod = prsncod;
	}

	


	public String getPeoplecode() {
		return peoplecode;
	}

	public void setPeoplecode(String peoplecode) {
		this.peoplecode = peoplecode;
	}

	public String getParntcode() {
		return parntcode;
	}

	public void setParntcode(String parntcode) {
		this.parntcode = parntcode;
	}

	public String getRptid() {
		return this.rptid;
	}

	public void setRptid(String rptid) {
		this.rptid = rptid;
	}

	public String getRedorptid() {
		return this.redorptid;
	}

	public void setRedorptid(String redorptid) {
		this.redorptid = redorptid;
	}

	public String getFntjrn() {
		return this.fntjrn;
	}

	public void setFntjrn(String fntjrn) {
		this.fntjrn = fntjrn;
	}

	public String getPrsnnam() {
		return this.prsnnam;
	}

	public void setPrsnnam(String prsnnam) {
		this.prsnnam = prsnnam;
	}

	public String getCredtyp() {
		return this.credtyp;
	}

	public void setCredtyp(String credtyp) {
		this.credtyp = credtyp;
	}

	public String getCredtno() {
		return this.credtno;
	}

	public void setCredtno(String credtno) {
		this.credtno = credtno;
	}

	public String getPrsncod() {
		return this.prsncod;
	}

	public void setPrsncod(String prsncod) {
		this.prsncod = prsncod;
	}

	public String getTelno() {
		return this.telno;
	}

	public void setTelno(String telno) {
		this.telno = telno;
	}

	public String getRpttyp() {
		return this.rpttyp;
	}

	public void setRpttyp(String rpttyp) {
		this.rpttyp = rpttyp;
	}

	public String getRptnam() {
		return this.rptnam;
	}

	public void setRptnam(String rptnam) {
		this.rptnam = rptnam;
	}

	public String getPrdcod() {
		return this.prdcod;
	}

	public void setPrdcod(String prdcod) {
		this.prdcod = prdcod;
	}

	public String getPrdnam() {
		return this.prdnam;
	}

	public void setPrdnam(String prdnam) {
		this.prdnam = prdnam;
	}

	public String getDatcmitori() {
		return this.datcmitori;
	}

	public void setDatcmitori(String datcmitori) {
		this.datcmitori = datcmitori;
	}

	public String getRptdte() {
		return this.rptdte;
	}

	public void setRptdte(String rptdte) {
		this.rptdte = rptdte;
	}

	public String getRpttim() {
		return this.rpttim;
	}

	public void setRpttim(String rpttim) {
		this.rpttim = rpttim;
	}

	public String getRptsta() {
		return this.rptsta;
	}

	public void setRptsta(String rptsta) {
		this.rptsta = rptsta;
	}

	public String getRptmoddte() {
		return this.rptmoddte;
	}

	public void setRptmoddte(String rptmoddte) {
		this.rptmoddte = rptmoddte;
	}

	public String getRptmodtim() {
		return this.rptmodtim;
	}

	public void setRptmodtim(String rptmodtim) {
		this.rptmodtim = rptmodtim;
	}

	public String getOrgno() {
		return this.orgno;
	}

	public void setOrgno(String orgno) {
		this.orgno = orgno;
	}


	public String getReqadrr() {
		return this.reqadrr;
	}

	public void setReqadrr(String reqadrr) {
		this.reqadrr = reqadrr;
	}

	public String getRtpadrr() {
		return this.rtpadrr;
	}

	public void setRtpadrr(String rtpadrr) {
		this.rtpadrr = rtpadrr;
	}

	public Object deepClone() {
		return CacheUtil.deepCloneObject(this);
	}

	public String getUsrid() {
		return usrid;
	}

	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	public String getP_usrid() {
		return p_usrid;
	}

	public void setP_usrid(String p_usrid) {
		this.p_usrid = p_usrid;
	}

	public String getCorgno() {
		return corgno;
	}

	public void setCorgno(String corgno) {
		this.corgno = corgno;
	}

	public String getCporgno() {
		return cporgno;
	}

	public void setCporgno(String cporgno) {
		this.cporgno = cporgno;
	}

	public WfDatCreditrpt(String rptid, String redorptid, String fntjrn, String prsnnam, String credtyp, String credtno,
			String prsncod, String telno, String rpttyp, String rptnam, String prdcod, String prdnam, String datcmitori,
			String rptdte, String rpttim, String rptsta, String rptmoddte, String rptmodtim, String peoplecode,
			String orgno, String parntcode, String reqadrr, String rtpadrr, String usrid, String p_usrid, String corgno,
			String cporgno) {
		super();
		this.rptid = rptid;
		this.redorptid = redorptid;
		this.fntjrn = fntjrn;
		this.prsnnam = prsnnam;
		this.credtyp = credtyp;
		this.credtno = credtno;
		this.prsncod = prsncod;
		this.telno = telno;
		this.rpttyp = rpttyp;
		this.rptnam = rptnam;
		this.prdcod = prdcod;
		this.prdnam = prdnam;
		this.datcmitori = datcmitori;
		this.rptdte = rptdte;
		this.rpttim = rpttim;
		this.rptsta = rptsta;
		this.rptmoddte = rptmoddte;
		this.rptmodtim = rptmodtim;
		this.peoplecode = peoplecode;
		this.orgno = orgno;
		this.parntcode = parntcode;
		this.reqadrr = reqadrr;
		this.rtpadrr = rtpadrr;
		this.usrid = usrid;
		this.p_usrid = p_usrid;
		this.corgno = corgno;
		this.cporgno = cporgno;
	}


	
	
}
