package com.test.gzt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-01-08T14:09:22.748+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", name = "QueryValidatorServices")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryValidatorServices {

    @WebResult(name = "querySingleReturn", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
    @RequestWrapper(localName = "querySingle", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "com.test.gzt.QuerySingle")
    @WebMethod
    @ResponseWrapper(localName = "querySingleResponse", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "com.test.gzt.QuerySingleResponse")
    public java.lang.String querySingle(
        @WebParam(name = "userName_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String userName,
        @WebParam(name = "password_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String password,
        @WebParam(name = "type_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String type,
        @WebParam(name = "param_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String param
    );

    @WebResult(name = "queryBatchReturn", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
    @RequestWrapper(localName = "queryBatch", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "com.test.gzt.QueryBatch")
    @WebMethod
    @ResponseWrapper(localName = "queryBatchResponse", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "com.test.gzt.QueryBatchResponse")
    public java.lang.String queryBatch(
        @WebParam(name = "userName_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String userName,
        @WebParam(name = "password_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String password,
        @WebParam(name = "type_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String type,
        @WebParam(name = "param_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String param
    );
}
