package com.sinoway.mcp.service.strade.gzt.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * QueryValidatorServicesService service = new QueryValidatorServicesService();
 * QueryValidatorServices portType = service.getQueryValidatorServices();
 * portType.querySingle(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "QueryValidatorServicesService", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", wsdlLocation = "http://gboss.id5.cn/services/QueryValidatorServices?wsdl")
public class QueryValidatorServicesService extends Service {

	private final static URL QUERYVALIDATORSERVICESSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.sinoway.mcp.service.strade.gzt.ws.QueryValidatorServicesService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sinoway.mcp.service.strade.gzt.ws.QueryValidatorServicesService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://gboss.id5.cn/services/QueryValidatorServices?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://gboss.id5.cn/services/QueryValidatorServices?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		QUERYVALIDATORSERVICESSERVICE_WSDL_LOCATION = url;
	}

	public QueryValidatorServicesService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public QueryValidatorServicesService() {
		super(QUERYVALIDATORSERVICESSERVICE_WSDL_LOCATION, new QName(
				"http://app.service.validator.businesses.gboss.id5.cn",
				"QueryValidatorServicesService"));
	}

	/**
	 * 
	 * @return returns QueryValidatorServices
	 */
	@WebEndpoint(name = "QueryValidatorServices")
	public QueryValidatorServices getQueryValidatorServices() {
		return super.getPort(new QName(
				"http://app.service.validator.businesses.gboss.id5.cn",
				"QueryValidatorServices"), QueryValidatorServices.class);
	}

}
