package com.test.yimei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-01-13T10:24:15.255+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "HD_GetAccess_TokenSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface HDGetAccessTokenSoap {

    /**
     * 获取ACCESS_TOKEN凭证
     */
    @WebResult(name = "GetACCESS_TOKENResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetACCESS_TOKEN", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetACCESSTOKEN")
    @WebMethod(operationName = "GetACCESS_TOKEN", action = "http://tempuri.org/GetACCESS_TOKEN")
    @ResponseWrapper(localName = "GetACCESS_TOKENResponse", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetACCESSTOKENResponse")
    public java.lang.String getACCESSTOKEN(
        @WebParam(name = "AppID", targetNamespace = "http://tempuri.org/")
        java.lang.String appID,
        @WebParam(name = "AppSecret", targetNamespace = "http://tempuri.org/")
        java.lang.String appSecret,
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );
}
