
package com.test.gzt;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-01-08T14:09:22.753+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
 
public class QueryValidatorServices_QueryValidatorServices_Server{

    protected QueryValidatorServices_QueryValidatorServices_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new QueryValidatorServicesImpl();
        String address = "http://gboss.id5.cn/services/QueryValidatorServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new QueryValidatorServices_QueryValidatorServices_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
