package com.test.yimei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-01-13T10:14:34.461+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "User_CheckServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface UserCheckServiceSoap {

    /**
     * 欠款查询
     */
    @WebResult(name = "Get_Be_Overdue_ArrearsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Be_Overdue_Arrears", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetBeOverdueArrears")
    @WebMethod(operationName = "Get_Be_Overdue_Arrears", action = "http://tempuri.org/Get_Be_Overdue_Arrears")
    @ResponseWrapper(localName = "Get_Be_Overdue_ArrearsResponse", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetBeOverdueArrearsResponse")
    public java.lang.String getBeOverdueArrears(
        @WebParam(name = "Phone", targetNamespace = "http://tempuri.org/")
        java.lang.String phone,
        @WebParam(name = "StarTime", targetNamespace = "http://tempuri.org/")
        java.lang.String starTime,
        @WebParam(name = "EndTime", targetNamespace = "http://tempuri.org/")
        java.lang.String endTime,
        @WebParam(name = "ACCESS_TOKEN", targetNamespace = "http://tempuri.org/")
        java.lang.String accessTOKEN
    );

    /**
     * 逾期平台详情
     */
    @WebResult(name = "Get_Be_Overdue_Platform_DetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Be_Overdue_Platform_Detail", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetBeOverduePlatformDetail")
    @WebMethod(operationName = "Get_Be_Overdue_Platform_Detail", action = "http://tempuri.org/Get_Be_Overdue_Platform_Detail")
    @ResponseWrapper(localName = "Get_Be_Overdue_Platform_DetailResponse", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetBeOverduePlatformDetailResponse")
    public java.lang.String getBeOverduePlatformDetail(
        @WebParam(name = "Phone", targetNamespace = "http://tempuri.org/")
        java.lang.String phone,
        @WebParam(name = "cycle", targetNamespace = "http://tempuri.org/")
        java.lang.String cycle,
        @WebParam(name = "ACCESS_TOKEN", targetNamespace = "http://tempuri.org/")
        java.lang.String accessTOKEN
    );

    /**
     * 逾期平台次数
     */
    @WebResult(name = "Get_Be_Overdue_PlatformResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Be_Overdue_Platform", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetBeOverduePlatform")
    @WebMethod(operationName = "Get_Be_Overdue_Platform", action = "http://tempuri.org/Get_Be_Overdue_Platform")
    @ResponseWrapper(localName = "Get_Be_Overdue_PlatformResponse", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetBeOverduePlatformResponse")
    public java.lang.String getBeOverduePlatform(
        @WebParam(name = "Phone", targetNamespace = "http://tempuri.org/")
        java.lang.String phone,
        @WebParam(name = "cycle", targetNamespace = "http://tempuri.org/")
        java.lang.String cycle,
        @WebParam(name = "ACCESS_TOKEN", targetNamespace = "http://tempuri.org/")
        java.lang.String accessTOKEN
    );

    /**
     * 逾期次数
     */
    @WebResult(name = "Get_Be_OverdueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Be_Overdue", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetBeOverdue")
    @WebMethod(operationName = "Get_Be_Overdue", action = "http://tempuri.org/Get_Be_Overdue")
    @ResponseWrapper(localName = "Get_Be_OverdueResponse", targetNamespace = "http://tempuri.org/", className = "com.test.yimei.GetBeOverdueResponse")
    public java.lang.String getBeOverdue(
        @WebParam(name = "Phone", targetNamespace = "http://tempuri.org/")
        java.lang.String phone,
        @WebParam(name = "cycle", targetNamespace = "http://tempuri.org/")
        java.lang.String cycle,
        @WebParam(name = "ACCESS_TOKEN", targetNamespace = "http://tempuri.org/")
        java.lang.String accessTOKEN
    );
}
