package com.sinoway.wrn.entity;
// default package
// Generated 2016-1-4 11:51:20 by Hibernate Tools 3.4.0.CR1

/**
 * WfDatCerditPrsn generated by hbm2java
 */
public class WfDatCerditPrsn implements java.io.Serializable {

	private String id;
	private String prsnnam;
	private String credtyp;
	private String credtno;
	private String prsncod;
	private String loantyp;
	private String loanamt;
	private String loanlmt;
	private String telno;
	private String repaydte;
	private String repaytyp;
	private String repayamt;
	private String prdcod;
	private String prdnam;
	private String loansrtdte;
	private String loanenddte;
	private String peoplecode;
	private String orgno;
	private String parntcode;
	private String sta;
	private String usrid;
	private String p_usrid;
	private String corgno;
	private String cporgno;

	public WfDatCerditPrsn() {

	}

	
	
	public WfDatCerditPrsn(String id, String prsnnam, String credtyp,
			String credtno, String prsncod, String loantyp, String loanamt,
			String loanlmt, String telno, String repaydte, String repaytyp,
			String repayamt, String prdcod, String prdnam, String loansrtdte,
			String loanenddte, String peoplecode, String orgno,
			String parntcode, String sta, String usrid, String p_usrid,
			String corgno, String cporgno) {
		super();
		this.id = id;
		this.prsnnam = prsnnam;
		this.credtyp = credtyp;
		this.credtno = credtno;
		this.prsncod = prsncod;
		this.loantyp = loantyp;
		this.loanamt = loanamt;
		this.loanlmt = loanlmt;
		this.telno = telno;
		this.repaydte = repaydte;
		this.repaytyp = repaytyp;
		this.repayamt = repayamt;
		this.prdcod = prdcod;
		this.prdnam = prdnam;
		this.loansrtdte = loansrtdte;
		this.loanenddte = loanenddte;
		this.peoplecode = peoplecode;
		this.orgno = orgno;
		this.parntcode = parntcode;
		this.sta = sta;
		this.usrid = usrid;
		this.p_usrid = p_usrid;
		this.corgno = corgno;
		this.cporgno = cporgno;
	}



	public WfDatCerditPrsn(String id, String prsnnam, String prsncod) {
		this.id = id;
		this.prsnnam = prsnnam;
		this.prsncod = prsncod;
	}

	public String getPeoplecode() {
		return peoplecode;
	}

	public void setPeoplecode(String peoplecode) {
		this.peoplecode = peoplecode;
	}

	public String getParntcode() {
		return parntcode;
	}

	public void setParntcode(String parntcode) {
		this.parntcode = parntcode;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPrsnnam() {
		return this.prsnnam;
	}

	public void setPrsnnam(String prsnnam) {
		this.prsnnam = prsnnam;
	}

	public String getCredtyp() {
		return this.credtyp;
	}

	public void setCredtyp(String credtyp) {
		this.credtyp = credtyp;
	}

	public String getCredtno() {
		return this.credtno;
	}

	public void setCredtno(String credtno) {
		this.credtno = credtno;
	}

	public String getPrsncod() {
		return this.prsncod;
	}

	public void setPrsncod(String prsncod) {
		this.prsncod = prsncod;
	}

	public String getLoantyp() {
		return this.loantyp;
	}

	public void setLoantyp(String loantyp) {
		this.loantyp = loantyp;
	}

	public String getLoanamt() {
		return this.loanamt;
	}

	public void setLoanamt(String loanamt) {
		this.loanamt = loanamt;
	}

	public String getLoanlmt() {
		return this.loanlmt;
	}

	public void setLoanlmt(String loanlmt) {
		this.loanlmt = loanlmt;
	}

	public String getPrdcod() {
		return this.prdcod;
	}

	public void setPrdcod(String prdcod) {
		this.prdcod = prdcod;
	}

	public String getPrdnam() {
		return this.prdnam;
	}

	public void setPrdnam(String prdnam) {
		this.prdnam = prdnam;
	}

	public String getLoansrtdte() {
		return this.loansrtdte;
	}

	public void setLoansrtdte(String loansrtdte) {
		this.loansrtdte = loansrtdte;
	}

	public String getLoanenddte() {
		return this.loanenddte;
	}

	public void setLoanenddte(String loanenddte) {
		this.loanenddte = loanenddte;
	}


	public String getOrgno() {
		return this.orgno;
	}

	public void setOrgno(String orgno) {
		this.orgno = orgno;
	}

	public String getSta() {
		return this.sta;
	}

	public void setSta(String sta) {
		this.sta = sta;
	}

	public String getUsrid() {
		return this.usrid;
	}

	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}



	public String getCorgno() {
		return this.corgno;
	}

	public void setCorgno(String corgno) {
		this.corgno = corgno;
	}

	public String getCporgno() {
		return this.cporgno;
	}

	public void setCporgno(String cporgno) {
		this.cporgno = cporgno;
	}

	public String getP_usrid() {
		return p_usrid;
	}

	public void setP_usrid(String p_usrid) {
		this.p_usrid = p_usrid;
	}



	public String getTelno() {
		return telno;
	}



	public void setTelno(String telno) {
		this.telno = telno;
	}



	public String getRepaydte() {
		return repaydte;
	}

	public void setRepaydte(String repaydte) {
		this.repaydte = repaydte;
	}

	public String getRepaytyp() {
		return repaytyp;
	}

	public void setRepaytyp(String repaytyp) {
		this.repaytyp = repaytyp;
	}

	public String getRepayamt() {
		return repayamt;
	}

	public void setRepayamt(String repayamt) {
		this.repayamt = repayamt;
	}

	
	
}
