package com.sinoway.mcp.service.strade.gzt.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "QueryValidatorServices", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
public interface QueryValidatorServices {

	/**
	 * 
	 * @param param
	 * @param userName
	 * @param type
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "querySingleReturn", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
	@RequestWrapper(localName = "querySingle", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "com.sinoway.mcp.service.strade.gzt.ws.QuerySingle")
	@ResponseWrapper(localName = "querySingleResponse", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "com.sinoway.mcp.service.strade.gzt.ws.QuerySingleResponse")
	public String querySingle(
			@WebParam(name = "userName_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") String userName,
			@WebParam(name = "password_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") String password,
			@WebParam(name = "type_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") String type,
			@WebParam(name = "param_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") String param);

	/**
	 * 
	 * @param param
	 * @param userName
	 * @param type
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "queryBatchReturn", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
	@RequestWrapper(localName = "queryBatch", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "com.sinoway.mcp.service.strade.gzt.ws.QueryBatch")
	@ResponseWrapper(localName = "queryBatchResponse", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "com.sinoway.mcp.service.strade.gzt.ws.QueryBatchResponse")
	public String queryBatch(
			@WebParam(name = "userName_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") String userName,
			@WebParam(name = "password_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") String password,
			@WebParam(name = "type_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") String type,
			@WebParam(name = "param_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn") String param);

}
