package com.sinoway.acc.entity;
// default package
// Generated 2015-12-11 16:04:03 by Hibernate Tools 3.4.0.CR1

/**
 * WfCfgdefCompinfo generated by hbm2java
 */
public class WfCfgdefCompinfo implements java.io.Serializable {

	private String id;
	private String compno;
	private String compnam;
	private String compaddr;
	private String prsnnam;
	private String phnone;
	private String strdte;
	private String enddte;
	private String comptyp;
	private String sta;

	public WfCfgdefCompinfo() {
	}

	public WfCfgdefCompinfo(String id) {
		this.id = id;
	}

	public WfCfgdefCompinfo(String id, String compno, String compnam, String compaddr,  String prsnnam, String phnone, String strdte,
			String enddte, String comptyp, String sta) {
		this.id = id;
		this.compno = compno;
		this.compnam = compnam;
		this.compaddr = compaddr;
		this.prsnnam = prsnnam;
		this.phnone = phnone;
		this.strdte = strdte;
		this.enddte = enddte;
		this.comptyp = comptyp;
		this.sta = sta;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCompno() {
		return this.compno;
	}

	public void setCompno(String compno) {
		this.compno = compno;
	}

	public String getCompnam() {
		return this.compnam;
	}

	public void setCompnam(String compnam) {
		this.compnam = compnam;
	}

	public String getPrsnnam() {
		return this.prsnnam;
	}

	public void setPrsnnam(String prsnnam) {
		this.prsnnam = prsnnam;
	}

	public String getPhnone() {
		return this.phnone;
	}

	public void setPhnone(String phnone) {
		this.phnone = phnone;
	}

	public String getStrdte() {
		return this.strdte;
	}

	public void setStrdte(String strdte) {
		this.strdte = strdte;
	}

	public String getEnddte() {
		return this.enddte;
	}

	public void setEnddte(String enddte) {
		this.enddte = enddte;
	}

	public String getComptyp() {
		return this.comptyp;
	}

	public void setComptyp(String comptyp) {
		this.comptyp = comptyp;
	}

	public String getSta() {
		return this.sta;
	}

	public void setSta(String sta) {
		this.sta = sta;
	}

	public String getCompaddr() {
		return compaddr;
	}

	public void setCompaddr(String compaddr) {
		this.compaddr = compaddr;
	}

	
}
