package com.sinoway.acc.entity;

import java.util.Date;

// default package
// Generated 2015-12-22 16:04:03 by Hibernate Tools 3.4.0.CR1

/**
 * WfCfgdefCompinfo generated by hbm2java
 */
public class WfCfgdefPwd implements java.io.Serializable {

	private String sid;
	private String pwd;  //新密码
	private String recentpasswordrecord; //原密码
	private Date lastchangepwdtime;    //更新时间
	private String peoplecode;         //用户编号
	private String confimPwd;//确认密码
	
	
	
	public WfCfgdefPwd(String sid, String pwd, String recentpasswordrecord,
			Date lastchangepwdtime, String peoplecode,String confimPwd) {
		super();
		this.sid = sid;
		this.pwd = pwd;
		this.recentpasswordrecord = recentpasswordrecord;
		this.lastchangepwdtime = lastchangepwdtime;
		this.peoplecode = peoplecode;
		this.confimPwd = confimPwd;
	}
	public WfCfgdefPwd() {
	}
	public String getSid() {
		return sid;
	}
	public void setSid(String sid) {
		this.sid = sid;
	}
	public String getPwd() {
		return pwd;
	}
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	public String getRecentpasswordrecord() {
		return recentpasswordrecord;
	}
	public void setRecentpasswordrecord(String recentpasswordrecord) {
		this.recentpasswordrecord = recentpasswordrecord;
	}
	public String getPeoplecode() {
		return peoplecode;
	}
	public void setPeoplecode(String peoplecode) {
		this.peoplecode = peoplecode;
	}
	public Date getLastchangepwdtime() {
		return lastchangepwdtime;
	}
	public void setLastchangepwdtime(Date lastchangepwdtime) {
		this.lastchangepwdtime = lastchangepwdtime;
	}
	public String getConfimPwd() {
		return confimPwd;
	}
	public void setConfimPwd(String confimPwd) {
		this.confimPwd = confimPwd;
	}
	
	


	
}
